version: '3.8'
services:
  tacticul-service:
    container_name: "tacticul"
    image: tacticul:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_OPTS=-Dmaven.repo.local=/root/.m2/repository -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true
    ports:
      - "8080:8080"
    depends_on:
      service-db:
        condition: service_healthy
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DDL_AUTO: ${DDL_AUTO}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      INIT_ADMIN_LOGIN: ${INIT_ADMIN_LOGIN}
      INIT_ADMIN_PASSWORD: ${INIT_ADMIN_PASSWORD}
      INIT_ADMIN_EMAIL: ${INIT_ADMIN_EMAIL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXP: ${JWT_EXP}
      SERVER_IP: ${SERVER_IP}
      SERVER_PORT: ${SERVER_PORT}
      RECOVERY_MAIL: ${RECOVERY_MAIL}
      RECOVERY_PASSWORD: ${RECOVERY_PASSWORD}
      RESET_PASSWORD_SCRIPT_PATH: ${RESET_PASSWORD_SCRIPT_PATH}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    volumes:
      - tacticul-static:/app/static
      - maven-repo:/root/.m2/repository

  service-db:
    container_name: "service-db"
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${PGUSER}
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
      command: >
        sh -c "apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8 && docker-entrypoint.sh postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "tacticul" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "15432:5432"
    volumes:
      - tacticul-service-db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  tacticul-service-db:
  tacticul-static:
  maven-repo: